### ISSUE TITLE
v0.0.3-hotfix-1 guild announce

### ISSUE THREAD

**Issue by Road-block** [okdecm/InvasionDetector#3]
`/id guild` doesn't seem to be working, at least when I'm the only one with the addon in guild.

`!id` in guild chat also does nothing.

`/id party` in a test group does work, as does the local chatframe prints with `/id` so I'm guessing the logic for routing to guild output is broken.

**Comment by Road-block** [comment]
For some extra info, no special characters in character name but on one of the realms with two word name.

**Comment by okdecm** [comment]
I'm going to make a fix to `/id guild` as it should just notify the guild via you rather than _attempt_ to notify the guild (which all online guild members will only get when an invasion update occurs).

Not so sure on `!id` :/

**Comment by okdecm** [comment]
Actually - you mention you are the only one in the guild with the addon... were you possibly in an instanced zone such as a dungeon or battleground?

**Comment by Road-block** [comment]
Sorry for late reply but no. I was in Stormwind.

**Comment by okdecm** [comment]
Looks like I had removed the bit of code which checks if the guild member had the addon thus can notify the guild of the invasion status. This meant if any invasion was spotted and somebody was online with a new lower-sorted alphabetical wise WITHOUT the addon, it would not notify the guild (even when using the `!id` command).

This was my doing during debugging, I've since pushed fixes for hopefully all of your issues and drafted a new hotfix release. Please let me know if there are any more issues.
